#!/usr/bin/env python3
import json, pan, sys
if len(sys.argv[1:]) < 3:
    p = lambda x: print(x.format(sys.argv[0]))
    p("Usage: {} PROVIDER METHOD ARGS...")
    p("  e.g. {} digitransit_hsl find_departures HSL:1020447")
    p("  e.g. {} digitransit_hsl find_lines HSL:1020447")
    p("  e.g. {} digitransit_hsl find_nearby_stops 24.943 60.167")
    p("  e.g. {} digitransit_hsl find_stops lasipalatsi 24.943 60.167")
    raise SystemExit(1)
def print_json(x):
    print(json.dumps(x, indent=4, sort_keys=True))
provider = pan.Provider(sys.argv[1])
if sys.argv[2] == "find_departures":
    print_json(provider.find_departures([sys.argv[3]]))
if sys.argv[2] == "find_lines":
    print_json(provider.find_lines([sys.argv[3]]))
if sys.argv[2] == "find_nearby_stops":
    x, y = map(float, sys.argv[3:5])
    print_json(provider.find_nearby_stops(x, y))
if sys.argv[2] == "find_stops":
    x, y = map(float, sys.argv[4:6])
    print_json(provider.find_stops(sys.argv[3], x, y))
